### PR TITLE
Add save track option

### PR DESCRIPTION
**Pull request by lmbringas**
Hi, I've just add save track option and i changed suggested_key of shuffle to Alt+Shift+S  because i think that is more intuitive now. 
I attached how i see the save icon

imagen

### CODE REVIEW

**Comment by TsunDoge** [comment]
Hi. The default hotkey for shuffle is not "Alt+Shift+S" due to Firefox using that keystroke for opening the History navbar, at least in Firefox Developer Edition.

As for adding the option to save the song, I have to make some changes in the configuration but I will implement it. Thanks

**Comment by TsunDoge** [comment]
Hi again. I was checking the correct behaviour of the new feature, but I doesn't work for me.
Looking at the Spotify web source code, the class `.spoticon-add-16` wasnt there. Instead I found `.spoticon-fav-16`.

Can you please tell me from what url are you accessing the site?

**Comment by lmbringas** [comment]
hi, this is url https://open.spotify.com/browse/featured. I'm using  Mozilla Firefox 65.0 and this is how i look the website.

imagen

**Comment by TsunDoge** [comment]
Kinda strange. I'm going to make some changes so that it works for us both. Once I have the new version I would ask you if it is possible for you to do some tests since I can not do it myself.

**Comment by lmbringas** [comment]
hey, you should check this [PR](https://github.com/beaufortfrancois/spotify-hotkeys-chrome-extension/pull/26). They have same issue but with different types of icons. 
Yes I'll test. thanks

**Comment by TsunDoge** [comment]
Added a query to check if `spoticon-heart`is present, if not use `.spoticon-add`.

Now it should work. Please try it and let me know before deploying the new version.

**Comment by lmbringas** [comment]
hey thanks. check that you added twice  `document.querySelector('.spoticon-add-16')` but one has to be `document.querySelector('.spoticon-added-16')`. if you change that it will work excellent.

**Comment by TsunDoge** [comment]
I'm going to upload the new version to firefox so in the next update this feature will be implemented. 
Thank you for your contribution and the testing.

**Pull request merged**
